# frozen_string_literal: true

# Flatpack and Recording Studio keep Tailwind class names in Ruby and ERB.
# Dummy @source globs that assume vendor/bundle or /usr/local/bundle miss this
# environment's Bundler gem path, so the compiled stylesheet ships almost no
# utilities. Resolve real gem roots at build time instead.
namespace :tailwindcss do
  desc "Write Bundler gem @source paths so Tailwind can scan Flatpack"
  task enhance_sources: :environment do
    css_path = Rails.root.join("app/assets/tailwind/gem_sources.css")
    lines = ["/* Generated by rake tailwindcss:enhance_sources. Do not edit. */"]

    gem_scan_roots = {
      "flat_pack" => ["app/components"],
      "recording_studio" => ["app/views"],
      "recording_studio_accessible" => ["app/views", "app/components"],
      "recording_studio_admin" => ["app/views", "app/components"],
      "recording_studio_ai" => ["app/views", "lib/recording_studio_ai/admin"],
      "recording_studio_agents" => ["app/views"],
      "recording_studio_root_switchable" => ["app/views"]
    }

    gem_scan_roots.each do |gem_name, relative_directories|
      spec = Gem.loaded_specs[gem_name]
      next unless spec

      relative_directories.each do |relative_directory|
        directory = File.join(spec.full_gem_path, relative_directory)
        next unless File.directory?(directory)

        glob = if relative_directory.include?("components") || relative_directory.include?("/admin")
                 "**/*.{rb,erb}"
               else
                 "**/*.erb"
               end
        lines << %(@source "#{directory}/#{glob}";)
      end
    end

    css_path.write("#{lines.join("\n")}\n")
  end
end

if Rake::Task.task_defined?("tailwindcss:build")
  Rake::Task["tailwindcss:build"].enhance(["tailwindcss:enhance_sources"])
end

if Rake::Task.task_defined?("tailwindcss:watch")
  Rake::Task["tailwindcss:watch"].enhance(["tailwindcss:enhance_sources"])
end
